### ISSUE TITLE
CalledProcessError: Command 'sh /tmp/tmpU_dLcN/run' returned non-zero exit status 2

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.recipe.cmd#7]
since yesterday we are having issues with the new version of ```collective.recipe.cmd```:

```python
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/travis/build/simplesconsultoria/sc.blog/buildout-cache/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1866, in main
    getattr(buildout, command)(args)
  File "/home/travis/build/simplesconsultoria/sc.blog/buildout-cache/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 625, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/travis/build/simplesconsultoria/sc.blog/buildout-cache/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1345, in _call
    return f()
  File "/home/travis/build/simplesconsultoria/sc.blog/buildout-cache/eggs/collective.recipe.cmd-0.8-py2.7.egg/collective/recipe/cmd/__init__.py", line 48, in install
    self.execute()
  File "/home/travis/build/simplesconsultoria/sc.blog/buildout-cache/eggs/collective.recipe.cmd-0.8-py2.7.egg/collective/recipe/cmd/__init__.py", line 61, in execute
    run_commands(cmds, self.shell)
  File "/home/travis/build/simplesconsultoria/sc.blog/buildout-cache/eggs/collective.recipe.cmd-0.8-py2.7.egg/collective/recipe/cmd/__init__.py", line 33, in run_commands
    check_call('%s %s' % (shell, tmpfile), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'sh /tmp/tmpU_dLcN/run' returned non-zero exit status 2
```

see https://s3.amazonaws.com/archive.travis-ci.org/jobs/14328253/log.txt

this is related with #6.

**Comment by gawel** [comment]
Dont really know if this still an issue

**Comment by hvelarde** [comment]
I'll try to test it today

**Comment by hvelarde** [comment]
the bug seem to be fixed; I'm having some interment problems on Travis CI but they seem not to be related with this.
